### PR TITLE
Wrapper for fully parameterized Tesseract Init

### PR DESCRIPTION
**Pull request by timvandekamp**

### CODE REVIEW

**Comment by ldiqual** [comment]
Hey Tim! This PR looks awesome! Just a few comments:
- Could you comment the new `init` method by indicating what the parameters are?
- I don't feel comfortable merging untested code into master. Could you please try it and confirm it works properly?

**Comment by timvandekamp** [comment]
I can totally do that. I was just thinking some doc comments would be good there. It will be awhile before I have time to test the config file part, but maybe I'll get to it this week.

**Comment by ldiqual** [comment]
Great! I look forward to it then ;)

**Comment by timvandekamp** [comment]
Time freed up much more quickly than expected. The code is now reasonably well tested :)

**Comment by ldiqual** [comment]
Love it. Thanks so much for your contribution! Merging.

**Pull request merged**
